ARG tag=20.12
FROM nvcr.io/nvidia/pytorch:${tag}-py3 AS base
ARG tag

ADD . /opt/exportlib
RUN pip install nvidia-pyindex && \
        pip install tritonclient[all] /opt/exportlib

RUN pip install /opt/exportlib
WORKDIR /opt/exportlib/tests/unit
ENTRYPOINT "pytest ."
