[tool.black]
line-length = 82
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "attrs"
known_first_party = ["exportlib"]
known_third_party = ["attr", "google", "tensorrt", "torch", "tritongrpcclient"]
