name: test

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: python tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run tests
        id: tests
        uses: ./
